//express is the framework we're going to use to handle requests
const express = require('express')
//Create a new instance of express
const app = express()

const router = require('express').Router();
const apiRoutes = require("./api/index");

/*
 * Serve the API documentation generated by apidoc as HTML. 
 * https://apidocjs.com/
 * 
 * Run the following in the terminal to update the apidoc for the endpoints: 
 * apidoc -i backend/api -o apidoc/
 */
app.use("/doc", express.static('../apidoc'))

/**
 * Sets up the API endpoint that starts before all other endpoints.
 */
router.use("/api", apiRoutes);

module.exports = router;